/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.training.amf.admin.monitor.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.training.amf.admin.monitor.model.StoreEvents;
import com.liferay.training.amf.admin.monitor.model.StoreEventsModel;
import com.liferay.training.amf.admin.monitor.model.StoreEventsSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the StoreEvents service. Represents a row in the &quot;StoreEvents_StoreEvents&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>StoreEventsModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link StoreEventsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StoreEventsImpl
 * @generated
 */
@JSON(strict = true)
public class StoreEventsModelImpl
	extends BaseModelImpl<StoreEvents> implements StoreEventsModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a store events model instance should use the <code>StoreEvents</code> interface instead.
	 */
	public static final String TABLE_NAME = "StoreEvents_StoreEvents";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"eventId", Types.BIGINT},
		{"logged", Types.TIMESTAMP}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"requestIp", Types.VARCHAR},
		{"eventType", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("eventId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("logged", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("requestIp", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("eventType", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table StoreEvents_StoreEvents (uuid_ VARCHAR(75) null,eventId LONG not null primary key,logged DATE null,userId LONG,userName VARCHAR(75) null,requestIp VARCHAR(75) null,eventType VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table StoreEvents_StoreEvents";

	public static final String ORDER_BY_JPQL =
		" ORDER BY storeEvents.logged DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY StoreEvents_StoreEvents.logged DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EVENTTYPE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LOGGED_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static StoreEvents toModel(StoreEventsSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		StoreEvents model = new StoreEventsImpl();

		model.setUuid(soapModel.getUuid());
		model.setEventId(soapModel.getEventId());
		model.setLogged(soapModel.getLogged());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setRequestIp(soapModel.getRequestIp());
		model.setEventType(soapModel.getEventType());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<StoreEvents> toModels(StoreEventsSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<StoreEvents> models = new ArrayList<StoreEvents>(
			soapModels.length);

		for (StoreEventsSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public StoreEventsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _eventId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEventId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _eventId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return StoreEvents.class;
	}

	@Override
	public String getModelClassName() {
		return StoreEvents.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<StoreEvents, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<StoreEvents, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<StoreEvents, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((StoreEvents)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<StoreEvents, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<StoreEvents, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(StoreEvents)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<StoreEvents, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<StoreEvents, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, StoreEvents>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			StoreEvents.class.getClassLoader(), StoreEvents.class,
			ModelWrapper.class);

		try {
			Constructor<StoreEvents> constructor =
				(Constructor<StoreEvents>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<StoreEvents, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<StoreEvents, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<StoreEvents, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<StoreEvents, Object>>();
		Map<String, BiConsumer<StoreEvents, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<StoreEvents, ?>>();

		attributeGetterFunctions.put("uuid", StoreEvents::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<StoreEvents, String>)StoreEvents::setUuid);
		attributeGetterFunctions.put("eventId", StoreEvents::getEventId);
		attributeSetterBiConsumers.put(
			"eventId", (BiConsumer<StoreEvents, Long>)StoreEvents::setEventId);
		attributeGetterFunctions.put("logged", StoreEvents::getLogged);
		attributeSetterBiConsumers.put(
			"logged", (BiConsumer<StoreEvents, Date>)StoreEvents::setLogged);
		attributeGetterFunctions.put("userId", StoreEvents::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<StoreEvents, Long>)StoreEvents::setUserId);
		attributeGetterFunctions.put("userName", StoreEvents::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<StoreEvents, String>)StoreEvents::setUserName);
		attributeGetterFunctions.put("requestIp", StoreEvents::getRequestIp);
		attributeSetterBiConsumers.put(
			"requestIp",
			(BiConsumer<StoreEvents, String>)StoreEvents::setRequestIp);
		attributeGetterFunctions.put("eventType", StoreEvents::getEventType);
		attributeSetterBiConsumers.put(
			"eventType",
			(BiConsumer<StoreEvents, String>)StoreEvents::setEventType);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getEventId() {
		return _eventId;
	}

	@Override
	public void setEventId(long eventId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_eventId = eventId;
	}

	@JSON
	@Override
	public Date getLogged() {
		return _logged;
	}

	@Override
	public void setLogged(Date logged) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_logged = logged;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalUserId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("userId"));
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public String getRequestIp() {
		if (_requestIp == null) {
			return "";
		}
		else {
			return _requestIp;
		}
	}

	@Override
	public void setRequestIp(String requestIp) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_requestIp = requestIp;
	}

	@JSON
	@Override
	public String getEventType() {
		if (_eventType == null) {
			return "";
		}
		else {
			return _eventType;
		}
	}

	@Override
	public void setEventType(String eventType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_eventType = eventType;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalEventType() {
		return getColumnOriginalValue("eventType");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, StoreEvents.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public StoreEvents toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, StoreEvents>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		StoreEventsImpl storeEventsImpl = new StoreEventsImpl();

		storeEventsImpl.setUuid(getUuid());
		storeEventsImpl.setEventId(getEventId());
		storeEventsImpl.setLogged(getLogged());
		storeEventsImpl.setUserId(getUserId());
		storeEventsImpl.setUserName(getUserName());
		storeEventsImpl.setRequestIp(getRequestIp());
		storeEventsImpl.setEventType(getEventType());

		storeEventsImpl.resetOriginalValues();

		return storeEventsImpl;
	}

	@Override
	public int compareTo(StoreEvents storeEvents) {
		int value = 0;

		value = DateUtil.compareTo(getLogged(), storeEvents.getLogged());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof StoreEvents)) {
			return false;
		}

		StoreEvents storeEvents = (StoreEvents)object;

		long primaryKey = storeEvents.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<StoreEvents> toCacheModel() {
		StoreEventsCacheModel storeEventsCacheModel =
			new StoreEventsCacheModel();

		storeEventsCacheModel.uuid = getUuid();

		String uuid = storeEventsCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			storeEventsCacheModel.uuid = null;
		}

		storeEventsCacheModel.eventId = getEventId();

		Date logged = getLogged();

		if (logged != null) {
			storeEventsCacheModel.logged = logged.getTime();
		}
		else {
			storeEventsCacheModel.logged = Long.MIN_VALUE;
		}

		storeEventsCacheModel.userId = getUserId();

		storeEventsCacheModel.userName = getUserName();

		String userName = storeEventsCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			storeEventsCacheModel.userName = null;
		}

		storeEventsCacheModel.requestIp = getRequestIp();

		String requestIp = storeEventsCacheModel.requestIp;

		if ((requestIp != null) && (requestIp.length() == 0)) {
			storeEventsCacheModel.requestIp = null;
		}

		storeEventsCacheModel.eventType = getEventType();

		String eventType = storeEventsCacheModel.eventType;

		if ((eventType != null) && (eventType.length() == 0)) {
			storeEventsCacheModel.eventType = null;
		}

		return storeEventsCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<StoreEvents, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<StoreEvents, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<StoreEvents, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((StoreEvents)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<StoreEvents, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<StoreEvents, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<StoreEvents, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((StoreEvents)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, StoreEvents>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _eventId;
	private Date _logged;
	private long _userId;
	private String _userName;
	private String _requestIp;
	private String _eventType;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<StoreEvents, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((StoreEvents)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("eventId", _eventId);
		_columnOriginalValues.put("logged", _logged);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("requestIp", _requestIp);
		_columnOriginalValues.put("eventType", _eventType);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("eventId", 2L);

		columnBitmasks.put("logged", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("requestIp", 32L);

		columnBitmasks.put("eventType", 64L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private StoreEvents _escapedModel;

}